version: 2

# https://docs.readthedocs.io/en/latest/yaml-config.html
formats:
  - htmlzip
  - epub

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

python:
  install:
    - requirements: ci/rtd-requirements.txt
    - method: pip
      path: .

sphinx:
  configuration: docs/source/conf.py
